[project]
name = "obsidian_to_hugo"
dynamic = ["version", "dependencies"]

[project.scripts]
# main = "obsidian-to-hugo.src.main"

[tool.setuptools.dynamic]
dependencies = { file = "requirements.txt" }
